# Generated by Django 5.2.3 on 2025-10-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='text2',
            field=models.CharField(default=0, max_length=50, verbose_name='Прикооол:'),
            preserve_default=False,
        ),
    ]
