# Generated by Django 5.2.5 on 2025-10-26 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_table_text2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.RemoveField(
            model_name='table',
            name='text2',
        ),
    ]
